import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

'''
Histograms

Author: Shaobo Wang

Use a histogram to plot at least three (3) of the variables (attributes) in either data set.
Discuss the insight generated by the histograms. What do they show or suggest?

'''


class Histogram:
    # data members
    file_name = ''
    data_frame = pd.DataFrame()

    # constructor
    def __init__(self, options):
        self.file_name = options[1]
        self.set_input_data()

    # read data from csv
    def set_input_data(self):
        self.data_frame = pd.read_csv(self.file_name)

    # get input data
    def get_input_data(self):
        return self.data_frame

    # plot histograms
    def hist(self):
        i = 0
        for column in self.data_frame.columns:
            if self.data_frame.dtypes[i] == 'int64':
                data = self.data_frame[column]
                data_list = list(data[pd.notnull(data)])
                # %matplotlib inline
                plt.figure()
                plt.hist(data_list)
                plt.title(column)
                plt.show()
                print(str(column) + " plotted")
            i += 1

